In [10]:
# Install tmdbsimple (only need to run once)
!pip install tmdbsimple

Requirement already satisfied: tmdbsimple in /Users/milkasantana/anaconda3/envs/dojo-env/lib/python3.9/site-packages (2.9.1)
Requirement already satisfied: requests in /Users/milkasantana/anaconda3/envs/dojo-env/lib/python3.9/site-packages (from tmdbsimple) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/milkasantana/anaconda3/envs/dojo-env/lib/python3.9/site-packages (from requests->tmdbsimple) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /Users/milkasantana/anaconda3/envs/dojo-env/lib/python3.9/site-packages (from requests->tmdbsimple) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /Users/milkasantana/anaconda3/envs/dojo-env/lib/python3.9/site-packages (from requests->tmdbsimple) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/milkasantana/anaconda3/envs/dojo-env/lib/python3.9/site-packages (from requests->tmdbsimple) (2.0.4)

In [11]:
import json
with open('/Users/milkasantana/.secret/tmdb_api.json', 'r') as f:
    login = json.load(f)
## Display the keys of the loaded dict
login.keys()

dict_keys(['api-key'])

In [12]:
import tmdbsimple as tmdb
tmdb.API_KEY =  login['api-key']

### Querying Movies by ID

In [13]:
## make a movie object using the .Movies function from tmdb
movie = tmdb.Movies(603)
movie

In [14]:
## movie objects have a .info dictionary 
info = movie.info()
info

{'adult': False,
 'backdrop_path': '/oMsxZEvz9a708d49b6UdZK1KAo5.jpg',
 'belongs_to_collection': {'id': 2344,
  'name': 'The Matrix Collection',
  'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg',
  'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'},
 'budget': 63000000,
 'genres': [{'id': 28, 'name': 'Action'},
  {'id': 878, 'name': 'Science Fiction'}],
 'homepage': 'http://www.warnerbros.com/matrix',
 'id': 603,
 'imdb_id': 'tt0133093',
 'original_language': 'en',
 'original_title': 'The Matrix',
 'overview': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
 'popularity': 83.249,
 'poster_path': '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
 'production_companies': [{'id': 79,
   'logo_path': '/tpFpsqbleCzEE2p5EgvUq6ozfCA.png',
   'name': 'Village Roadshow Pictures',
   'origin_country': 'US'},
  {'id': 372,
   'logo_path': None,
   'name': 'Groucho II Film Partnership',
   'origin_country': ''},
  {'id': 1885,
   'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png',
   'name': 'Silver Pictures',
   'origin_country': 'US'},
  {'id': 174,
   'logo_path': '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
   'name': 'Warner Bros. Pictures',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '1999-03-30',
 'revenue': 463517383,
 'runtime': 136,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Welcome to the Real World.',
 'title': 'The Matrix',
 'video': False,
 'vote_average': 8.206,
 'vote_count': 23605}

In [15]:
info['budget']

63000000

In [16]:
info['revenue']

463517383

In [17]:
info['imdb_id']

'tt0133093'

In [18]:
movie = tmdb.Movies('tt1361336')
info = movie.info()
info['budget']

50000000

In [19]:
response =movie.releases()

In [20]:
response

{'id': 587807,
 'countries': [{'certification': '',
   'descriptors': [],
   'iso_3166_1': 'CO',
   'primary': False,
   'release_date': '2021-02-12'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'US',
   'primary': False,
   'release_date': '2021-02-26'},
  {'certification': 'ALL',
   'descriptors': [],
   'iso_3166_1': 'KR',
   'primary': False,
   'release_date': '2021-02-24'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'ID',
   'primary': False,
   'release_date': '2021-03-10'},
  {'certification': '6',
   'descriptors': [],
   'iso_3166_1': 'NL',
   'primary': False,
   'release_date': '2021-06-09'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'IE',
   'primary': False,
   'release_date': '2021-05-07'},
  {'certification': 'M/6',
   'descriptors': [],
   'iso_3166_1': 'PT',
   'primary': False,
   'release_date': '2021-03-04'},
  {'certification': '6+',
   'descriptors': [],
   'iso_3166_1': 'RU',
   'primary': False,
   'release_date': '2021-02-25'},
  {'certification': 'L',
   'descriptors': [],
   'iso_3166_1': 'BR',
   'primary': False,
   'release_date': '2021-02-11'},
  {'certification': '7',
   'descriptors': [],
   'iso_3166_1': 'DK',
   'primary': False,
   'release_date': '2021-02-11'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'AU',
   'primary': False,
   'release_date': '2021-04-01'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'HK',
   'primary': False,
   'release_date': '2021-03-11'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2021-05-19'},
  {'certification': 'Btl',
   'descriptors': [],
   'iso_3166_1': 'SE',
   'primary': False,
   'release_date': '2021-05-28'},
  {'certification': '0',
   'descriptors': [],
   'iso_3166_1': 'DE',
   'primary': False,
   'release_date': '2021-06-17'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'CZ',
   'primary': False,
   'release_date': '2021-06-10'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'SK',
   'primary': False,
   'release_date': '2021-05-27'},
  {'certification': 'V',
   'descriptors': [],
   'iso_3166_1': 'LT',
   'primary': False,
   'release_date': '2021-05-07'},
  {'certification': '6',
   'descriptors': [],
   'iso_3166_1': 'HU',
   'primary': False,
   'release_date': '2021-05-20'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'PL',
   'primary': False,
   'release_date': '2021-06-11'},
  {'certification': '7',
   'descriptors': [],
   'iso_3166_1': 'ES',
   'primary': False,
   'release_date': '2021-03-26'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'SG',
   'primary': False,
   'release_date': '2021-02-11'},
  {'certification': 'Κ',
   'descriptors': [],
   'iso_3166_1': 'GR',
   'primary': False,
   'release_date': '2021-06-10'},
  {'certification': '普遍級',
   'descriptors': [],
   'iso_3166_1': 'TW',
   'primary': False,
   'release_date': '2021-02-10'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'KZ',
   'primary': False,
   'release_date': '2021-02-25'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'US',
   'primary': False,
   'release_date': '2021-02-26'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'GB',
   'primary': False,
   'release_date': '2021-03-25'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'AU',
   'primary': False,
   'release_date': '2021-06-01'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'NZ',
   'primary': False,
   'release_date': '2021-06-01'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2021-09-16'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2022-02-16'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'GB',
   'primary': False,
   'release_date': '2021-05-24'},
  {'certification': 'G',
   'descriptors': [],
   'iso_3166_1': 'AU',
   'primary': False,
   'release_date': '2021-06-21'},
  {'certification': 'PG',
   'descriptors': [],
   'iso_3166_1': 'US',
   'primary': False,
   'release_date': '2021-05-18'},
  {'certification': 'U',
   'descriptors': [],
   'iso_3166_1': 'FR',
   'primary': False,
   'release_date': '2021-09-22'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'GR',
   'primary': False,
   'release_date': '2021-09-23'},
  {'certification': '',
   'descriptors': [],
   'iso_3166_1': 'CA',
   'primary': False,
   'release_date': '2021-07-31'}]}

### Saving the Movie Certification/MPAA Rating

In [21]:
# example from package README
# source = https://github.com/celiao/tmdbsimple
releases = movie.releases()
for c in releases['countries']:
    if c['iso_3166_1'] == 'US':
        print(c['certification'])

PG
PG
PG

In [22]:
# Get the movie object for the current id
movie = tmdb.Movies('tt1361336')
# save the .info .releases dictionaries
info = movie.info()
releases = movie.releases()
# Loop through countries in releases
for c in releases['countries']:
    # if the country abbreviation==US
    if c['iso_3166_1' ] =='US':
        ## save a "certification" key in the info dict with the certification
       info['certification'] = c['certification']

### Defining Our Function

In [23]:
def get_movie_with_rating(movie_id):
    #movie = tmdb.Movies('tt1361336')
    movie = tmdb.Movies(movie_id)
    info = movie.info()
    releases = movie.releases()
    for c in releases ['countries']:
        if c['iso_3166_1'] =='US':
            info['certification'] =c['certification']
    return info

In [24]:
info

{'adult': False,
 'backdrop_path': '/9ns9463dwOeo1CK1JU2wirL5Yi1.jpg',
 'belongs_to_collection': None,
 'budget': 50000000,
 'genres': [{'id': 35, 'name': 'Comedy'},
  {'id': 10751, 'name': 'Family'},
  {'id': 16, 'name': 'Animation'}],
 'homepage': 'https://www.tomandjerrymovie.com',
 'id': 587807,
 'imdb_id': 'tt1361336',
 'original_language': 'en',
 'original_title': 'Tom & Jerry',
 'overview': 'Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.',
 'popularity': 65.708,
 'poster_path': '/8XZI9QZ7Pm3fVkigWJPbrXCMzjq.jpg',
 'production_companies': [{'id': 25120,
   'logo_path': '/lMj6nMJBOzfLEd2fu8uF530AJcv.png',
   'name': 'Warner Bros. Pictures Animation',
   'origin_country': 'US'},
  {'id': 8922,
   'logo_path': '/yZWehAyjfKi4KvKeg1bkJ1bm5H8.png',
   'name': 'Turner Entertainment',
   'origin_country': 'US'},
  {'id': 77061,
   'logo_path': None,
   'name': 'The Story Company',
   'origin_country': 'US'},
  {'id': 174,
   'logo_path': '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
   'name': 'Warner Bros. Pictures',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2021-02-10',
 'revenue': 136536687,
 'runtime': 101,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Best of enemies. Worst of friends.',
 'title': 'Tom & Jerry',
 'video': False,
 'vote_average': 6.871,
 'vote_count': 2256,
 'certification': 'PG'}

### Testing Our Function

In [25]:
# Now test your function on "The Avengers" (id="tt0848228"). What is its certification?
test = get_movie_with_rating('tt0848228') #put your function name here
test

{'adult': False,
 'backdrop_path': '/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
 'belongs_to_collection': {'id': 86311,
  'name': 'The Avengers Collection',
  'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
  'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
 'budget': 220000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://www.marvel.com/movies/the-avengers',
 'id': 24428,
 'imdb_id': 'tt0848228',
 'original_language': 'en',
 'original_title': 'The Avengers',
 'overview': 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
 'popularity': 124.742,
 'poster_path': '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2012-04-25',
 'revenue': 1518815515,
 'runtime': 143,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'},
  {'english_name': 'Hindi', 'iso_639_1': 'hi', 'name': 'हिन्दी'},
  {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
 'status': 'Released',
 'tagline': 'Some assembly required.',
 'title': 'The Avengers',
 'video': False,
 'vote_average': 7.711,
 'vote_count': 28970,
 'certification': 'PG-13'}

## PART II : LOOPING

In [48]:
import pandas as pd
import os, time,json
import tmdbsimple as tmdb 
from tqdm.notebook import tqdm_notebook
FOLDER = "Data/"
os.makedirs(FOLDER, exist_ok=True)
os.listdir(FOLDER)

['DataProject3',
 'File Location.ipynb',
 'tmdb_api_results_2000.json',
 'final_tmdb_data_2000.csv.gz',
 'tmdb_api_results_2001.json',
 'title_basics.csv.gz',
 'final_tmdb_data_2001.csv.gz',
 '.ipynb_checkpoints',
 'tmdb_api_results_2000.csv',
 'title_akas.csv.gz',
 'tmdb_results_combined.csv.gz',
 'title_ratings.csv.gz']

In [49]:
YEARS_TO_GET = [2000,2001]

In [50]:
# Load in the dataframe from project part 1 as basics:
basics = pd.read_csv('Data/title_basics.csv.gz')

In [63]:
def write_json(new_data, filename): 
    """Appends a list of records (new_data) to a json file (filename). 
    Adapted from: https://www.geeksforgeeks.org/append-to-json-file-using-python/"""  
    
    with open(filename,'r+') as file:
        # First we load existing data into a dict.
        file_data = json.load(file)
        ## Choose extend or append
        if (type(new_data) == list) & (type(file_data) == list):
            file_data.extend(new_data)
        else:
             file_data.append(new_data)
        # Sets file's current position at offset.
        file.seek(0)
        # convert back to json.
        json.dump(file_data, file)

In [47]:
errors = [ ]

In [64]:
# Start of OUTER loop
for YEAR in tqdm_notebook(YEARS_TO_GET, desc='YEARS', position=0):
    #Defining the JSON file to store results for year
    JSON_FILE = f'{FOLDER}tmdb_api_results_{YEAR}.json'
    # Check if file exists
    file_exists = os.path.isfile(JSON_FILE)
    # If it does not exist: create it
    if file_exists == False:
    # save an empty dict with just "imdb_id" to the new json file.
        with open(JSON_FILE,'w') as f:
            json.dump([{'imdb_id':0}],f)
    #Saving new year as the current df
    df = basics.loc[ basics['startYear']==YEAR].copy()
    # saving movie ids to list
    movie_ids = df['tconst'].copy()
    # Load existing data from json into a dataframe called "previous_df"
    previous_df = pd.read_json(JSON_FILE)
    # filter out any ids that are already in the JSON_FILE
    movie_ids_to_get = movie_ids[~movie_ids.isin(previous_df['imdb_id'])]
    
    #Get index and movie id from list
    # INNER Loop
    for movie_id in tqdm_notebook(movie_ids_to_get,
                                  desc=f'Movies from {YEAR}',
                                  position=1,
                                  leave=True):
        try:
            # Retrieve then data for the movie id
            temp = get_movie_with_rating(movie_id)  
            # Append/extend results to existing file using a pre-made function
            write_json(temp,JSON_FILE)
            # Short 20 ms sleep to prevent overwhelming server
            time.sleep(0.02)
            
        except Exception as e:
            errors.append([movie_id, e])
            
    final_year_df = pd.read_json(JSON_FILE)
    final_year_df.to_csv(f"{FOLDER}final_tmdb_data_{YEAR}.csv.gz", compression="gzip", index=False)

YEARS:   0%|          | 0/2 [00:00<?, ?it/s]

Movies from 2000:   0%|          | 0/1454 [00:00<?, ?it/s]

Movies from 2001:   0%|          | 0/1573 [00:00<?, ?it/s]

In [ ]:
print(f"- Total errors: {len(errors)}")

### PART III Exploratory Data Analysis

In [27]:
# Define the paths 
file_path_2000 = '/Users/milkasantana/Documents/GitHub/IMDB_Project/Data/final_tmdb_data_2000.csv.gz'

# Load the CSV files into separate DataFrames
df_2000 = pd.read_csv(file_path_2000, compression='gzip')
df_2000

,imdb_id,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,certification
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0113026,0.0,/vMFs7nw6P0bIV1jDsQpxAieAVnH.jpg,NaN,10000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,62127.0,en,The Fantasticks,...,0.0,86.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Try to remember the first time magic happened,The Fantasticks,0.0,5.50,22.0,NaN
2,tt0113092,0.0,NaN,NaN,0.0,"[{'id': 878, 'name': 'Science Fiction'}]",NaN,110977.0,en,For the Cause,...,0.0,100.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The ultimate showdown on a forbidden planet.,For the Cause,0.0,5.45,10.0,NaN
3,tt0116391,0.0,NaN,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,442869.0,hi,Gang,...,0.0,152.0,"[{'english_name': 'Hindi', 'iso_639_1': 'hi', ...",Released,NaN,Gang,0.0,4.00,1.0,NaN
4,tt0118694,0.0,/n4GJFGzsc7NinI1VeGDXIcQjtU2.jpg,NaN,150000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,843.0,cn,花樣年華,...,14204632.0,99.0,"[{'english_name': 'Cantonese', 'iso_639_1': 'c...",Released,"Feel the heat, keep the feeling burning, let t...",In the Mood for Love,0.0,8.11,2278.0,PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,tt6174238,0.0,NaN,NaN,0.0,"[{'id': 80, 'name': 'Crime'}]",NaN,223878.0,cn,冷战,...,0.0,0.0,"[{'english_name': 'Cantonese', 'iso_639_1': 'c...",Released,NaN,Cold War,0.0,2.00,2.0,NaN
1244,tt7029820,0.0,NaN,NaN,7000.0,[],NaN,604889.0,en,Scream For Christmas,...,0.0,80.0,[],Released,NaN,Scream For Christmas,0.0,0.00,0.0,NaN
1245,tt7197642,0.0,NaN,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}]",NaN,872676.0,en,"Goodbye, Merry-Go-Round",...,0.0,90.0,[],Released,NaN,"Goodbye, Merry-Go-Round",0.0,0.00,0.0,NaN
1246,tt7631368,0.0,/sF0gUHE0YzZNXYugTB2LFxJIppf.jpg,NaN,10000000.0,"[{'id': 27, 'name': 'Horror'}]",NaN,97186.0,fr,"I, Vampire",...,0.0,85.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,"I, Vampire",0.0,6.40,4.0,NR
1247,tt7802790,0.0,/etxml2M8GQzb31jcH0cdA489WCX.jpg,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,610992.0,fa,مومیایی ۳,...,0.0,98.0,"[{'english_name': 'Persian', 'iso_639_1': 'fa'...",Released,NaN,The Mummy 3,0.0,7.00,1.0,NaN

In [28]:
# Define the paths 
file_path_2001 = '/Users/milkasantana/Documents/GitHub/IMDB_Project/Data/final_tmdb_data_2001.csv.gz'

# Load the CSV files into separate DataFrames
df_2001 = pd.read_csv(file_path_2001, compression='gzip')
df_2001

,imdb_id,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,certification
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0035423,0.0,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,NaN,48000000.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 14, ...",NaN,11232.0,en,Kate & Leopold,...,76019048.0,118.0,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,"If they lived in the same century, they'd be p...",Kate & Leopold,0.0,6.331,1213.0,PG-13
2,tt0114447,0.0,NaN,NaN,0.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",NaN,151007.0,en,The Silent Force,...,0.0,90.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,They left him for dead... They should have fin...,The Silent Force,0.0,5.000,3.0,NaN
3,tt0116916,0.0,/rFpHBidSlhjflmnLu7BZilyKeQR.jpg,NaN,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,73549.0,en,The Dark Mist,...,0.0,101.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,The Dark Mist,0.0,3.500,2.0,PG
4,tt0118589,0.0,/9NZAirJahVilTiDNCHLFcdkwkiy.jpg,NaN,22000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,10696.0,en,Glitter,...,5271666.0,104.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"In music she found her dream, her love, herself.",Glitter,0.0,4.438,129.0,PG-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337,tt7797790,0.0,NaN,NaN,0.0,"[{'id': 27, 'name': 'Horror'}]",NaN,956219.0,en,Edmund Kemper Part 3: La mort sévit,...,0.0,72.0,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,NaN,Edmund Kemper Part 3: La mort sévit,0.0,0.000,0.0,NaN
1338,tt8665056,0.0,NaN,NaN,0.0,"[{'id': 37, 'name': 'Western'}]",http://skeletoncreekproductions.com/p-movie-br...,885436.0,en,Guns Along The Bravo,...,0.0,85.0,[],Released,Evil came to the Southwest until three blazing...,Guns Along The Bravo,0.0,0.000,0.0,NaN
1339,tt8795764,0.0,NaN,NaN,0.0,"[{'id': 27, 'name': 'Horror'}]",https://www.utahwolf.com/films/coming-soon-new...,871624.0,en,New Breed,...,0.0,57.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,New Breed,0.0,0.000,0.0,NR
1340,tt9071078,0.0,NaN,NaN,0.0,"[{'id': 28, 'name': 'Action'}]",NaN,201706.0,cn,致命密函,...,0.0,90.0,"[{'english_name': 'Cantonese', 'iso_639_1': 'c...",Released,NaN,Chinese Heroes,0.0,3.000,2.0,NaN
1341,tt9212730,0.0,NaN,NaN,0.0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,382630.0,ja,実録外伝 ゾンビ極道,...,0.0,88.0,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,NaN,Yakuza Zombie,0.0,0.000,0.0,NaN

In [29]:
# Concatenate the DataFrames
concatenated_df = pd.concat([df_2000, df_2001], ignore_index=True)
pd.set_option('display.max_columns', None)  # Display all columns
concatenated_df

,imdb_id,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,certification
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0113026,0.0,/vMFs7nw6P0bIV1jDsQpxAieAVnH.jpg,NaN,10000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,62127.0,en,The Fantasticks,Two rural teens sing and dance their way throu...,2.065,/hfO64mXz3DgUxkBVU7no2UWRP7x.jpg,"[{'id': 51207, 'logo_path': None, 'name': 'Sul...","[{'iso_3166_1': 'US', 'name': 'United States o...",2000-09-22,0.0,86.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Try to remember the first time magic happened,The Fantasticks,0.0,5.50,22.0,NaN
2,tt0113092,0.0,NaN,NaN,0.0,"[{'id': 878, 'name': 'Science Fiction'}]",NaN,110977.0,en,For the Cause,Earth is in a state of constant war and two co...,1.761,/h9bWO13nWRGZJo4XVPiElXyrRMU.jpg,"[{'id': 7405, 'logo_path': '/rfnws0uY8rsNAsrLb...","[{'iso_3166_1': 'US', 'name': 'United States o...",2000-11-15,0.0,100.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The ultimate showdown on a forbidden planet.,For the Cause,0.0,5.45,10.0,NaN
3,tt0116391,0.0,NaN,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,442869.0,hi,Gang,"After falling prey to underworld, four friends...",0.665,/yB5wRu4uyXXwZA3PEj8cITu0xt3.jpg,[],"[{'iso_3166_1': 'IN', 'name': 'India'}]",2000-04-14,0.0,152.0,"[{'english_name': 'Hindi', 'iso_639_1': 'hi', ...",Released,NaN,Gang,0.0,4.00,1.0,NaN
4,tt0118694,0.0,/n4GJFGzsc7NinI1VeGDXIcQjtU2.jpg,NaN,150000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,843.0,cn,花樣年華,Two neighbors become intimate after discoverin...,27.301,/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg,"[{'id': 539, 'logo_path': '/iPLtePguIzOPNtAWfT...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2000-09-29,14204632.0,99.0,"[{'english_name': 'Cantonese', 'iso_639_1': 'c...",Released,"Feel the heat, keep the feeling burning, let t...",In the Mood for Love,0.0,8.11,2278.0,PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2585,tt7797790,0.0,NaN,NaN,0.0,"[{'id': 27, 'name': 'Horror'}]",NaN,956219.0,en,Edmund Kemper Part 3: La mort sévit,Underground French necrophilia nastiness,0.600,/75kV4BpVnXe2kAMsWAKxx466M88.jpg,"[{'id': 139554, 'logo_path': None, 'name': 'Am...","[{'iso_3166_1': 'FR', 'name': 'France'}]",2001-01-01,0.0,72.0,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,NaN,Edmund Kemper Part 3: La mort sévit,0.0,0.00,0.0,NaN
2586,tt8665056,0.0,NaN,NaN,0.0,"[{'id': 37, 'name': 'Western'}]",http://skeletoncreekproductions.com/p-movie-br...,885436.0,en,Guns Along The Bravo,In the 1880's a ruthess gang of outlaws terroi...,0.600,NaN,"[{'id': 68934, 'logo_path': None, 'name': 'Ske...","[{'iso_3166_1': 'US', 'name': 'United States o...",2001-10-10,0.0,85.0,[],Released,Evil came to the Southwest until three blazing...,Guns Along The Bravo,0.0,0.00,0.0,NaN
2587,tt8795764,0.0,NaN,NaN,0.0,"[{'id': 27, 'name': 'Horror'}]",https://www.utahwolf.com/films/coming-soon-new...,871624.0,en,New Breed,Derek gets sucked into a gothic cult that turn...,0.600,/goddglRmgDgQuo9tlMdoeeHlRfX.jpg,"[{'id': 133614, 'logo_path': None, 'name': 'Wo...","[{'iso_3166_1': 'US', 'name': 'United States o...",2001-01-01,0.0,57.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,New Breed,0.0,0.00,0.0,NR
2588,tt9071078,0.0,NaN,NaN,0.0,"[{'id': 28, 'name': 'Action'}]",NaN,201706.0,cn,致命密函,A good-natured kung fu kid gets caught up in c...,1.736,/aO5ZupdPuOyIhHbhZCHzldh2Dvp.jpg,"[{'id': 13958, 'logo_path': '/yblRwoxf2sGIzzWV...","[{'iso_3166_1': 'HK', 'name': 'Hong Kong'}]",2001-07-12,0.0,90.0,"[{'english_name': 'Cantonese', 'iso_639_1': 'c...",Released,NaN,Chinese Heroes,0.0,3.00,2.0,NaN
2589,tt9212730,0.0,NaN,NaN,0.0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,382630.0,ja,実録外伝 ゾンビ極道,Yakuza Zombie opens with an introduction to a ...,0.600,/2UxCpo1R2IcCF7c8KkZDvt81JbS.jpg,"[{'id': 73158, 'logo_path': None, 'name': 'Jap...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",2001-02-15,0.0,88.0,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,NaN,Yakuza Zombie,0.0,0.00,0.0,NaN

# FEEDBACK: Make sure that your resulting. oncated dataframe when starting the EDA portion has 2.5-2.7 rows

### 1. How many movies had at least some valid financial information (values > 0 for budget OR revenue)?
- Please exclude any movies with 0's for budget AND revenue from the remaining visualizations.

In [30]:

# Filter out rows with both budget and revenue as 0
financial_df = concatenated_df[(concatenated_df['budget'] > 0) | (concatenated_df['revenue'] > 0)]

# Count them
movies_valid_info = len(financial_df)

In [31]:
movies_valid_info

645

# FEEDBACK: Properly answer question 2-4

### 2. How many movies are there in each of the certification categories (G/PG/PG-13/R)?

In [32]:
# Group the DataFrame by certification and count the number of movies in each category
certification_counts = concatenated_df['certification'].value_counts()

# Print the result
print("Number of movies in each certification category:")
print(certification_counts)

Number of movies in each certification category:
R          465
PG-13      182
NR          73
PG          62
G           25
NC-17        6
Unrated      1
Name: certification, dtype: int64

### 3. What is the average revenue per certification category?

In [33]:
# DataFrame by certification and calculate the average revenue 
avg_rev_certification = concatenated_df.groupby('certification')['revenue'].mean()

avg_rev_certification

certification
G          7.041886e+07
NC-17      0.000000e+00
NR         4.838643e+06
PG         6.248013e+07
PG-13      7.146544e+07
R          1.491408e+07
Unrated    0.000000e+00
Name: revenue, dtype: float64

### 4. What is the average budget per certification category?

In [34]:
avg_budget_certification = concatenated_df.groupby('certification')['budget'].mean()

avg_budget_certification

certification
G          2.288000e+07
NC-17      0.000000e+00
NR         2.778563e+06
PG         2.530641e+07
PG-13      3.094592e+07
R          9.317859e+06
Unrated    0.000000e+00
Name: budget, dtype: float64